name: Run vulneralbility testing
# Event trigger
on:
 push:
  branches:
   - main
 pull_request:
    types: [closed]
    branches:
      - main
jobs:
  securityCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          
        with:
          command: monitor --org=$ORG_NAME --file=requirements.txt -- --allow-missing
