name: Run vulneralbility testing
# Event trigger
on:
 push:
  branches:
   - main
 pull_request:
    types: [closed]
    branches:
      - main
jobs:
  securityCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
        with:
          command: | 
                  auth 9e903390-4437-4cee-be6f-16ce1c41a1f0 
                  code test --org=org --file=requirements.txt -- --allow-missing 
